fix(RocketChatClientCallBuilder): fix proxy access without credentials (JENKINS-55890)
Including refactoring to improve code quality
and to reduce complexity of different execution paths.

Also fixes:
org.apache.http.conn.UnsupportedSchemeException: http protocol is not supported
when using proxy (with or without auth) and trustSSL is active.

Also switches from deprecated SSLSocketFactory to SSLConnectionSocketFactory.